services:
  - type: web
    name: fitnotes-viewer-api
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
