export const TRAINING_INTENT_EXAMPLES = [
  example('greeting', 'hello'),
  example('greeting', 'hi there'),
  example('greeting', 'hey coach'),
  example('greeting', 'olá'),
  example('greeting', 'bom dia'),
  example('greeting', 'boa tarde'),

  example('help', 'what can you answer'),
  example('help', 'what can I ask'),
  example('help', 'how can you help me'),
  example('help', 'show available questions'),
  example('help', 'o que posso perguntar'),
  example('help', 'como podes ajudar'),
  example('help', 'o que sabes fazer'),

  example('summary', 'summarize my training'),
  example('summary', 'summarize my workouts'),
  example('summary', 'give me a training overview'),
  example('summary', 'how is my training going'),
  example('summary', 'resume o meu treino'),
  example('summary', 'faz um resumo dos meus treinos'),
  example('summary', 'como está o meu treino'),

  example('total-sets', 'how many sets did I do'),
  example('total-sets', 'tell me my total sets'),
  example('total-sets', 'number of logged sets'),
  example('total-sets', 'quantos sets fiz'),
  example('total-sets', 'qual é o total de séries'),
  example('total-sets', 'diz os meus sets'),

  example('total-reps', 'how many reps did I do'),
  example('total-reps', 'tell me my total reps'),
  example('total-reps', 'what is my repetition count'),
  example('total-reps', 'quantas repetições fiz'),
  example('total-reps', 'qual é o total de reps'),
  example('total-reps', 'diz as minhas repetições'),

  example('workout-count', 'how many workouts did I do'),
  example('workout-count', 'how often did I train'),
  example('workout-count', 'tell me my workout count'),
  example('workout-count', 'quantos treinos fiz'),
  example('workout-count', 'quantas vezes treinei'),
  example('workout-count', 'em quantos dias treinei'),

  example('average-sets', 'what is my average sets per workout'),
  example('average-sets', 'how many sets do I average'),
  example('average-sets', 'average workout size'),
  example('average-sets', 'qual é a média de sets por treino'),
  example('average-sets', 'quantos sets faço em média'),
  example('average-sets', 'média de séries por treino'),

  example('frequency', 'what is my muscle training frequency'),
  example('frequency', 'how frequently do I train each muscle'),
  example('frequency', 'muscle workout frequency'),
  example('frequency', 'qual é a frequência dos músculos'),
  example('frequency', 'quantas vezes treino cada músculo'),
  example('frequency', 'frequência de treino muscular'),

  example('top-muscle', 'what is my most trained muscle'),
  example('top-muscle', 'which muscle did I train most'),
  example('top-muscle', 'show my top muscle'),
  example('top-muscle', 'qual músculo treinei mais'),
  example('top-muscle', 'qual é o músculo mais treinado'),
  example('top-muscle', 'meu músculo principal'),

  example('least-muscle', 'what is my least trained muscle'),
  example('least-muscle', 'which muscle did I train the least'),
  example('least-muscle', 'show my lowest muscle'),
  example('least-muscle', 'qual músculo treinei menos'),
  example('least-muscle', 'qual é o músculo menos treinado'),
  example('least-muscle', 'músculo com menos sets'),

  example('top-exercise', 'what is my most used exercise'),
  example('top-exercise', 'which exercise did I do most'),
  example('top-exercise', 'show my top exercise'),
  example('top-exercise', 'qual exercício fiz mais'),
  example('top-exercise', 'qual é o exercício mais usado'),
  example('top-exercise', 'exercício que mais repeti'),

  example('volume', 'what is my total training volume'),
  example('volume', 'how much weight did I lift'),
  example('volume', 'tell me my workout volume'),
  example('volume', 'qual é o volume total'),
  example('volume', 'quanto peso levantei'),
  example('volume', 'diz o meu volume de treino'),

  example('progress', 'how many progress sets do I have'),
  example('progress', 'am I making progress'),
  example('progress', 'show my progression'),
  example('progress', 'quantos sets de progresso tenho'),
  example('progress', 'estou a progredir'),
  example('progress', 'mostra a minha evolução'),

  example('recent-workout', 'what was my latest workout'),
  example('recent-workout', 'show my most recent training day'),
  example('recent-workout', 'tell me about my last workout'),
  example('recent-workout', 'qual foi o meu último treino'),
  example('recent-workout', 'mostra o treino mais recente'),
  example('recent-workout', 'como foi o último dia de treino'),

  example('best-set', 'what was my best set'),
  example('best-set', 'show my heaviest set'),
  example('best-set', 'what is my maximum weight'),
  example('best-set', 'qual foi o meu melhor set'),
  example('best-set', 'mostra o set com mais peso'),
  example('best-set', 'qual é o meu peso máximo'),

  example('date-range', 'what date range are you analysing'),
  example('date-range', 'when does my history start'),
  example('date-range', 'show the full date range'),
  example('date-range', 'qual é o intervalo analisado'),
  example('date-range', 'quando começa o meu histórico'),
  example('date-range', 'que período estás a analisar'),

  example('distribution', 'how are my sets distributed'),
  example('distribution', 'is my muscle balance even'),
  example('distribution', 'show my muscle distribution'),
  example('distribution', 'como estão distribuídos os sets'),
  example('distribution', 'o treino está equilibrado'),
  example('distribution', 'mostra a distribuição muscular'),

  example('advice', 'how can I improve my training'),
  example('advice', 'give me a training suggestion'),
  example('advice', 'what should I improve'),
  example('advice', 'como posso melhorar o treino'),
  example('advice', 'dá-me uma sugestão'),
  example('advice', 'o que devo melhorar'),
]

function example(intent, text) {
  return { intent, text }
}
